#user:
#  id: 1
#  username: Demon
#  isAdmin: true
#  maps: {key: value, key2: value2}
#  list:
#    - Jia
#    - Fie
#  account:
#    accountId: 277
#    balance: 123456789

server:
  port: 8081


spring:
  profiles:
    active: prod

---

server:
  port: 8083

spring:
  profiles: dev

---

server:
  port: 8085

spring:
  profiles: prod