spring:
  datasource:
    username: root
    password: 1234567
    url: jdbc:mysql:///test?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # druid 相关配置
    druid:
      # 配置监控页功能
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false
      # 监控 web
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js, *.gif, *.jpg, *.png, *.css, *.ico, /druid/*'
        session-stat-enable: true
      # 监控 spring bean
      aop-patterns: org.demon.*
      # 开启底层功能 stat, wall
      filters: stat, wall
      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false
