spring:
  datasource:
    url: jdbc:mysql:///test?serverTimezone=Asia/Shanghai
    username: root
    password: 1234567
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost # 默认其实就是 localhost

mybatis:
  configuration:
    map-underscore-to-camel-case: true

# 将该包的 debug 模式打开即可显示 sql 语句
logging:
  level.org.demon.mapper: debug

# 开启自动配置文档
# debug: true
