spring:
  datasource:
    username: root
    password: 1234567
    url: jdbc:mysql:///test?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: true
    testWhileIdle: false
    testOnBorrow: false
    testOneReturn: false
    poolPreparedStatements: true
    # \u914D\u7F6E\u76D1\u63A7 filter, \u4F7F sql \u7EDF\u8BA1\u751F\u6548\uFF0C\u8BB0\u5F97\u5BFC\u5165 log4j \u4F9D\u8D56
    filters: stat, wall, log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#    initialization-mode: always
#    schema:
#      - classpath:sql/department.sql
#      - classpath:sql/employee.sql
mybatis:
  config-location: classpath:mybatis/mybatis_config.xml # \u6307\u5B9A mybatis \u5168\u5C40\u914D\u7F6E\u6587\u4EF6
  mapper-locations: classpath:mybatis/mapper/*.xml # \u6307\u5B9A mybatis mapper \u6620\u5C04\u6587\u4EF6

