spring:
  datasource:
    url: jdbc:mysql:///test?serverTimezone=Asia/Shanghai
    username: root
    password: 1234567
    driver-class-name: com.mysql.cj.jdbc.Driver
#    schema:
#      - classpath:department.sql
#      - classpath:employee.sql
#    initialization-mode: always