spring:
  datasource:
    username: root
    password: 1234567
    url: jdbc:mysql:///test?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: true
    testWhileIdle: false
    testOnBorrow: false
    testOneReturn: false
    poolPreparedStatements: true
    # 配置监控 filter, 使 sql 统计生效，记得导入 log4j 依赖
    filters: stat, wall, log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#    initialization-mode: always
#    schema:
#      - classpath:sql/department.sql
#      - classpath:sql/employee.sql
mybatis:
  # config-location: classpath:mybatis/mybatis_config.xml # 指定 mybatis 全局配置文件
  mapper-locations: classpath:mybatis/mapper/*.xml # 指定 mybatis mapper映射文件
  configuration: # 代替全局配置文件
    map-underscore-to-camel-case: true # 开启驼峰命名法

